# Generated by Django 5.2.17 on 2026-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_looser_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster image shown instantly while video loads. Highly recommended.', null=True, upload_to='hero/posters/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Compressed MP4 (H.264) recommended. Keep under 8-12 MB for fast loading.', null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload mp4 video testimonial', null=True, upload_to='testimonials/videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or YouTube/Vimeo URL'),
        ),
    ]
