# Generated by Django 5.2.17 on 2026-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_looser_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedesign',
            name='category',
            field=models.CharField(choices=[('Single Storey', 'Single Storey'), ('Double Storey', 'Double Storey'), ('Duplex', 'Duplex')], default='Single Storey', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='depth',
            field=models.CharField(blank=True, help_text='Depth in metres', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='frontage',
            field=models.CharField(blank=True, help_text='Width in metres, e.g. 12.5', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='house_size',
            field=models.CharField(blank=True, help_text='Floor area in m², e.g. 190.04', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='land_size',
            field=models.CharField(blank=True, help_text='Land area in m²', max_length=50),
        ),
        migrations.AlterField(
            model_name='homedesign',
            name='min_lot_width',
            field=models.CharField(blank=True, help_text='Minimum lot width in metres', max_length=50),
        ),
    ]
